apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-admin
spec:
  serviceName: pg-admin-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
      - name: pg-admin
        image: dpage/pgadmin4
        imagePullPolicy: Always
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: pg-admin-config
                key: pgadmin-email
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
             secretKeyRef:
               name: pg-admin-secret
               key: pgadmin-password
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
         - name: pg-admin-config
           mountPath: /pgadmin4/servers.json
           subPath: servers.json
           readOnly: true
         - name: pgadmin-data
           mountPath: /var/lib/pgadmin
      volumes:
             - name: pg-admin-config
               configMap:
                 name: pg-admin-config
  volumeClaimTemplates:
  - metadata:
     name: pgadmin-data
    spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 3Gi
                              
       
        
